#!/usr/bin/env bash
# ============================================================================
# Agentic Ads Platform - Local Setup Script
# ============================================================================
# This script sets up everything needed to run the platform locally.
# It creates directories, installs dependencies, and validates the setup.
#
# Usage:
#   ./scripts/setup.sh           # Full setup
#   ./scripts/setup.sh --quick   # Skip dependency install (if already done)
# ============================================================================

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

cd "$PROJECT_ROOT"

echo -e "${BLUE}"
echo "╔═══════════════════════════════════════════════════════════════════════╗"
echo "║           CREATIVE ADS PLATFORM - LOCAL SETUP                        ║"
echo "╚═══════════════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# ============================================================================
# Helper Functions
# ============================================================================

log_step() {
    echo -e "${GREEN}[✓]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[⚠]${NC} $1"
}

log_error() {
    echo -e "${RED}[✗]${NC} $1"
}

log_info() {
    echo -e "${BLUE}[ℹ]${NC} $1"
}

check_command() {
    if command -v "$1" &> /dev/null; then
        return 0
    else
        return 1
    fi
}

# ============================================================================
# 1. Check Prerequisites
# ============================================================================

echo ""
echo -e "${YELLOW}Step 1: Checking Prerequisites${NC}"
echo "─────────────────────────────────────────"

MISSING_DEPS=()

if check_command python3; then
    PYTHON_VERSION=$(python3 --version 2>&1 | cut -d' ' -f2)
    log_step "Python 3 found: $PYTHON_VERSION"
else
    MISSING_DEPS+=("python3")
    log_error "Python 3 not found"
fi

if check_command node; then
    NODE_VERSION=$(node --version)
    log_step "Node.js found: $NODE_VERSION"
else
    MISSING_DEPS+=("node")
    log_error "Node.js not found"
fi

if check_command npm; then
    NPM_VERSION=$(npm --version)
    log_step "npm found: $NPM_VERSION"
else
    MISSING_DEPS+=("npm")
    log_error "npm not found"
fi

if [ ${#MISSING_DEPS[@]} -gt 0 ]; then
    echo ""
    log_error "Missing dependencies: ${MISSING_DEPS[*]}"
    echo "Please install the missing dependencies and run this script again."
    exit 1
fi

# ============================================================================
# 2. Create Data Directories
# ============================================================================

echo ""
echo -e "${YELLOW}Step 2: Creating Data Directories${NC}"
echo "─────────────────────────────────────────"

mkdir -p data/{db,assets/raw,assets/processed,logs,metrics}
log_step "Created data/db/"
log_step "Created data/assets/raw/"
log_step "Created data/assets/processed/"
log_step "Created data/logs/"
log_step "Created data/metrics/"

# Create scrapers logs directory
mkdir -p scrapers/logs
log_step "Created scrapers/logs/"

# ============================================================================
# 3. Create .env File
# ============================================================================

echo ""
echo -e "${YELLOW}Step 3: Creating Environment File${NC}"
echo "─────────────────────────────────────────"

if [ ! -f .env ]; then
    cat > .env << 'EOF'
# ============================================================================
# Agentic Ads Platform - Local Development Environment
# Generated by setup.sh
# ============================================================================

# Mode: 'local' (default) or 'cloud'
MODE=local

# Local data directory
DATA_DIR=./data

# LLM mode: 'template' (default, deterministic) or 'ollama' (local AI)
# WARNING: 'vertex' is NOT allowed in local mode!
LLM_MODE=template

# Logging
LOG_LEVEL=INFO

# Low-RAM settings (conservative defaults)
MAX_BROWSER_INSTANCES=1
SEQUENTIAL_SCRAPING=true
GLOBAL_JOB_CAP=100
MAX_QUEUE_SIZE=1000
MAX_ASSETS_IN_MEMORY=50

# Scraper settings
HEADLESS=true
REQUEST_DELAY_MS=1000
PAGE_TIMEOUT_MS=30000

# Dashboard
DASHBOARD_PORT=8080
API_PORT=8081

# Concurrent jobs
MAX_CONCURRENT_JOBS=5
EOF
    log_step "Created .env file with local defaults"
else
    log_info ".env file already exists, skipping"
fi

# ============================================================================
# 4. Install Python Dependencies (if not --quick)
# ============================================================================

if [ "$1" != "--quick" ]; then
    echo ""
    echo -e "${YELLOW}Step 4: Installing Python Dependencies${NC}"
    echo "─────────────────────────────────────────"

    # Check for virtual environment
    if [ ! -d "venv" ]; then
        log_info "Creating Python virtual environment..."
        python3 -m venv venv
        log_step "Virtual environment created"
    else
        log_info "Virtual environment already exists"
    fi

    # Activate and install
    source venv/bin/activate
    log_step "Activated virtual environment"

    pip install --upgrade pip > /dev/null 2>&1
    pip install -r requirements.txt > /dev/null 2>&1
    log_step "Installed Python dependencies"

    # ============================================================================
    # 5. Install Node.js Dependencies
    # ============================================================================

    echo ""
    echo -e "${YELLOW}Step 5: Installing Node.js Dependencies${NC}"
    echo "─────────────────────────────────────────"

    cd scrapers
    npm install > /dev/null 2>&1
    log_step "Installed Node.js dependencies for scrapers"

    # Install Playwright browsers
    if [ "$SKIP_PLAYWRIGHT" != "true" ]; then
        log_info "Installing Playwright browsers (this may take a while)..."
        npx playwright install chromium > /dev/null 2>&1
        log_step "Installed Playwright Chromium browser"
    else
        log_warning "Skipping Playwright browser install (SKIP_PLAYWRIGHT=true)"
    fi

    cd "$PROJECT_ROOT"
else
    log_info "Skipping dependency installation (--quick mode)"
fi

# ============================================================================
# 6. Validate Setup
# ============================================================================

echo ""
echo -e "${YELLOW}Step 6: Validating Setup${NC}"
echo "─────────────────────────────────────────"

# Check if venv exists and is activated
if [ -d "venv" ]; then
    source venv/bin/activate
fi

# Test Python imports
if python3 -c "from agent.config import Config, Mode; print('Python imports OK')" 2>/dev/null; then
    log_step "Python imports validated"
else
    log_warning "Python imports may have issues - run 'python scripts/validate.py' for details"
fi

# Check if scrapers node_modules exist
if [ -d "scrapers/node_modules" ]; then
    log_step "Node.js modules installed"
else
    log_warning "Node.js modules not found in scrapers/"
fi

# ============================================================================
# Summary
# ============================================================================

echo ""
echo -e "${GREEN}"
echo "╔═══════════════════════════════════════════════════════════════════════╗"
echo "║                      SETUP COMPLETE! 🎉                              ║"
echo "╚═══════════════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

echo ""
echo "Next steps:"
echo ""
echo "  1. Activate the virtual environment:"
echo "     ${BLUE}source venv/bin/activate${NC}"
echo ""
echo "  2. Run validation script:"
echo "     ${BLUE}python scripts/validate.py${NC}"
echo ""
echo "  3. Start the platform in local mode:"
echo "     ${BLUE}python main.py${NC}"
echo ""
echo "  4. (Optional) Start with Docker:"
echo "     ${BLUE}docker-compose up${NC}"
echo ""
echo "Documentation: ${BLUE}docs/architecture.md${NC}"
echo ""

